
## INSERTING DATA INTO DATABASE PROCEDURE
DELIMITER //
CREATE PROCEDURE `PROC_INSERT_LOGS`(
IN IN_DEVICE_NAME VARCHAR(100),
IN IN_DISCRIPTION VARCHAR(200),
IN IN_PD_INDEX INT,
IN IN_INTERFACE_TYPE VARCHAR(30),
IN IN_MEDIA_TYPE VARCHAR(20),
IN IN_MODEL VARCHAR(100),
IN IN_PARTITIONS SMALLINT,
IN IN_SERIAL_NUMBER VARCHAR(100),
IN IN_SIZE BIGINT ,

IN NOTHING_TO_DO_WITH_THIS_VARIABLE VARCHAR(200),

IN IN_PERIPHERAL_DEVICE_TYPE VARCHAR(30),

IN IN_HOST_NAME VARCHAR(200),
IN IN_USER_NAME VARCHAR(200),
IN IN_IP_ADDRESS VARCHAR(30),
IN IN_MAC_ADDRESS VARCHAR(20),

IN IN_SOURCE_ADDRESS VARCHAR(500),
IN IN_DESTINATION_ADDRESS VARCHAR(500),
IN IN_FILE_SIZE bigint,
IN IN_TIME_OF_ACTION TIME,
IN IN_DATE_OF_ACTION DATE,
IN IN_OPERATION_PERFORMED VARCHAR(100),
IN IN_MESSAGE_DIGEST VARCHAR(116)
)
BEGIN

######################################################################################################################
## DECLARATION
DECLARE ROW_COUNT INT;
DECLARE IN_PD_DETAILS_ID INT;
DECLARE IN_PERIPHERAL_DEVICE_ID INT;
DECLARE IN_CLIENT_ID INT;



######################################################################################################################
### CHECKING WHEATHER THAT VALUE IS PRESENT IN THE DATABASE OR NOT. FLAG = 1 IF YES AND 0 IF NO

## PERIPHERAL DEVICE DETAILS INSERTION
SET ROW_COUNT = (SELECT COUNT(*) FROM `peripheral_device_details` WHERE `SERIAL_NUMBER` = IN_SERIAL_NUMBER);
### IF FLAG = 0 THEN ENTERING INTO THE DATABASE
IF(ROW_COUNT <> 1) THEN
 INSERT INTO peripheral_device_details (`MEDIA_TYPE`,`INTERFACE_TYPE`,`PD_INDEX`,`DISCRIPTION`,`MODEL`,`DEVICE_NAME`,`PARTITIONS`,`SERIAL_NUMBER`,`SIZE`) VALUES (IN_MEDIA_TYPE,IN_INTERFACE_TYPE,IN_PD_INDEX,IN_DISCRIPTION,IN_MODEL,IN_DEVICE_NAME,IN_PARTITIONS,IN_SERIAL_NUMBER,IN_SIZE);
 END IF;
 
 SET IN_PD_DETAILS_ID = (SELECT `PD_DETAILS_ID` FROM peripheral_device_details WHERE SERIAL_NUMBER = IN_SERIAL_NUMBER);
 
 
######################################################################################################################
### CHECKING WHEATHER THAT VALUE IS PRESENT IN THE DATASBASE OR NOT.  FLAG = 1 IF YES AND 0 IF NO

## PERIPHERAL DEVICE INSERTION

SET ROW_COUNT = (SELECT COUNT(*) FROM `peripheral_device` WHERE `PERIPHERAL_DEVICE_TYPE` =  IN_PERIPHERAL_DEVICE_TYPE);
### IF FLAG = 0 THEN ENTERING INTO THE DATABASE
IF(ROW_COUNT <> 1) THEN
INSERT INTO peripheral_device (PERIPHERAL_DEVICE_TYPE) VALUES (IN_PERIPHERAL_DEVICE_TYPE);
END IF;

SET IN_PERIPHERAL_DEVICE_ID = (SELECT `PERIPHERAL_DEVICE_ID` FROM peripheral_device WHERE PERIPHERAL_DEVICE_TYPE = IN_PERIPHERAL_DEVICE_TYPE);


######################################################################################################################### CHECKING WHEATHER THAT VALUE IS PRESENT IN THE DATABASE OR NOT.FLAG = 1 IF YES AND 0 IF NO


## CLIENT TABLE INSERTION

SET ROW_COUNT = (SELECT COUNT(*) FROM `client_table` WHERE `HOST_NAME` = IN_HOST_NAME AND `USER_NAME` = IN_USER_NAME AND `IP_ADDRESS` = IN_IP_ADDRESS AND `MAC_ADDRESS` = IN_MAC_ADDRESS);
### IF FLAG = 0 THEN ENTERING INTO THE DATABASE

IF(ROW_COUNT <> 1) THEN
INSERT INTO client_table (HOST_NAME,USER_NAME,IP_ADDRESS,MAC_ADDRESS) VALUES (IN_HOST_NAME,IN_USER_NAME,IN_IP_ADDRESS,IN_MAC_ADDRESS);
END IF;


SET IN_CLIENT_ID = (SELECT `CLIENT_ID` FROM client_table WHERE `HOST_NAME` = IN_HOST_NAME AND `USER_NAME` = IN_USER_NAME AND `IP_ADDRESS` = IN_IP_ADDRESS AND `MAC_ADDRESS` = IN_MAC_ADDRESS);

######################################################################################################################


### FINAL INSERTION


 INSERT INTO action_table (CLIENT_ID,DEVICE_TYPE_ID,PD_DETAILS_ID,SOURCE_ADDRESS,DESTINATION_ADDRESS,FILE_SIZE,TIME_OF_ACTION,DATE_OF_ACTION,OPERATION_PERFORMED,MESSAGE_DIGEST) VALUES (IN_CLIENT_ID,IN_PERIPHERAL_DEVICE_ID,IN_PD_DETAILS_ID,IN_SOURCE_ADDRESS,IN_DESTINATION_ADDRESS,IN_FILE_SIZE,IN_TIME_OF_ACTION,IN_DATE_OF_ACTION,IN_OPERATION_PERFORMED,IN_MESSAGE_DIGEST);
 
END //
DELIMITER ;
